// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct sensors s_sensors = {42, 42, 42};
void glue_get_sensors(struct sensors *data) {
  *data = s_sensors;  // Sync with your device
}
void glue_set_sensors(struct sensors *data) {
  s_sensors = *data; // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static struct leds s_leds = {false, 42, 42, 42};
void glue_get_leds(struct leds *data) {
  *data = s_leds;  // Sync with your device
}
void glue_set_leds(struct leds *data) {
  s_leds = *data; // Sync with your device
}

// Do not edit! See https://mongoose.ws/docs/guides/web-ui-builder/#custom-api-handlers
static uint64_t s_action_timeout_save_event;  // Time when save_event ends
bool glue_check_save_event(void) {
  return s_action_timeout_save_event > mg_now(); // Return true if save_event is in progress
}
void glue_start_save_event(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_save_event = mg_now() + 1000; // Start save_event, finish after 1 second
}

void glue_reply_events(struct mg_connection *c, struct mg_http_message *hm) {
  const char *headers = "Cache-Control: no-cache\r\n" "Content-Type: application/json\r\n";
  const char *value = "[{\"id\":0,\"timestamp\":12345,\"message\":\"Something failed\",\"priority\":2,\"status\":\"active\",\"notes\":\"some notes\"},{\"id\":1,\"timestamp\":12395,\"message\":\"Something succeeded\",\"priority\":1,\"status\":\"processed\",\"notes\":\"\"}]";
  (void) hm;
  mg_http_reply(c, 200, headers, "%s\n", value);
}